In [1]:
import pandas as pd 
from pathlib import Path

In [2]:
df = pd.read_csv("data.csv", encoding='latin')

In [3]:
df.shape

(40925, 133)

In [4]:
df.head(3)

,Unnamed: 0,FECHA,CODIGO,FLAG_MORA_TEMPRANA_8D_3M,NRO_ENTS_SF,NRO_ENTS_DIRECTA_SF,NRO_ENTS_DIRECT_1000_SF,NRO_ENTS_LT_TC_SF,NRO_ENTS_CONS_TC_SF,NRO_ENTS_CONS_DISPEFECT_TC_SF,...,BANCOP,NOBANCOP,ENTIMES,ENTI3M,ENTI6M,ENTI9M,ENTI12M,ANTIGUEDAD_MESES,RAT_SAL_ACT,RAT_PATR_ACT
0,281606,2023-07-31,100737574.0,1,2.0,2.0,2.0,0.0,0.0,0.0,...,NaN,S,NaN,NaN,NaN,NaN,NaN,NaN,1.695.197.872.340.420,1.0
1,95309,2024-03-31,125025137.0,0,1.0,1.0,0.0,0.0,0.0,0.0,...,NaN,S,NaN,NaN,NaN,NaN,NaN,NaN,135.762.264.150.943,1.0
2,210478,2024-04-30,198788490.0,0,3.0,3.0,3.0,0.0,0.0,0.0,...,NaN,S,NaN,NaN,NaN,NaN,NaN,NaN,3.673.126.744.186.040,6.523.372.093.023.250

In [6]:
df.FECHA.value_counts().sort_index()

FECHA
2022-01-31     830
2022-02-28     806
2022-03-31    1007
2022-04-30     874
2022-05-31     925
2022-06-30     842
2022-07-31     785
2022-08-31     837
2022-09-30     867
2022-10-31     791
2022-11-30     913
2022-12-31     982
2023-01-31     893
2023-02-28     888
2023-03-31    1075
2023-04-30     878
2023-05-31     987
2023-06-30     952
2023-07-31     942
2023-08-31    1044
2023-09-30     960
2023-10-31     965
2023-11-30    1023
2023-12-31     959
2024-01-31     969
2024-02-29    1005
2024-03-31     990
2024-04-30    1027
2024-05-31    1064
2024-06-30     999
2024-07-31    1054
2024-08-31    1064
2024-09-30    1066
2024-10-31    1128
2024-11-30    1135
2024-12-31    1328
2025-01-31    1184
2025-02-28    1167
2025-03-31    1325
2025-04-30    1218
2025-05-31    1177
Name: count, dtype: int64

In [7]:
df['FECHA'].dtype

dtype('O')

In [8]:
#convertir columna FECHA a datetime
df['FECHA'] = pd.to_datetime(df['FECHA'], format="%Y-%m-%d", errors="coerce")

In [9]:
df1 = df.loc[df['FECHA'] <= '2024-01-01']

In [11]:
df2 = df1.iloc[:, :50]

In [14]:
df2 = df2.drop(columns=['Unnamed: 0'])

In [15]:
df2.shape

(22025, 49)

In [16]:
df2.head(3)

,FECHA,CODIGO,FLAG_MORA_TEMPRANA_8D_3M,NRO_ENTS_SF,NRO_ENTS_DIRECTA_SF,NRO_ENTS_DIRECT_1000_SF,NRO_ENTS_LT_TC_SF,NRO_ENTS_CONS_TC_SF,NRO_ENTS_CONS_DISPEFECT_TC_SF,NRO_ENTS_HIP_SF,...,VAR_12M_MED_DIRECTA_CNS,VAR_12M_PROM_DEUDA,VAR_12M_MAX_DEUDA,VAR_12M_MED_DEUDA,VAR_6M_PROM_DIRECTA_CNS_TC,VAR_6M_MAX_DIRECTA_CNS_TC,VAR_6M_MED_DIRECTA_CNS_TC,VAR_6M_PROM_DIRECTA,VAR_6M_MAX_DIRECTA,VAR_6M_MED_DIRECTA
0,2023-07-31,100737574.0,1,2.0,2.0,2.0,0.0,0.0,0.0,0.0,...,796.743,383.722.966.220.753,165.581,696.743,0.0,0.0,0.0,144.783.763.481.659,327.905,216.965.932.078.985
5,2023-11-30,224497318.0,0,2.0,2.0,1.0,0.0,0.0,0.0,0.0,...,0.0,NaN,72.593,145.186,0.0,0.0,0.0,95.186,47.593,95.186
7,2022-05-31,41829028.0,0,2.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,-624.502.365.584.858,-783.538.019.469.895,-737.285.953.192.823,0.0,0.0,0.0,-688.663.288.793.452,-737.285.953.192.823,-689.114.814.529.246

In [17]:
df2.to_parquet("data_ejm.parquet", engine='pyarrow', index=False)